### ISSUE TITLE
1.13.x unit tests broken with v4.1.4

### ISSUE THREAD

**Issue by blimmer** [jamesarosen/ember-i18n#338]
I'm getting this error when trying to run unit tests with the latest version:
```
TypeError: Cannot read property 'i18n' of undefined
    at null._initDefaults (http://localhost:7357/assets/vendor.js:156069:33)
    at Object.sendEvent (http://localhost:7357/assets/vendor.js:27775:25)
    at new Class (http://localhost:7357/assets/vendor.js:48811:25)
    at Function.ClassMixinProps.create (http://localhost:7357/assets/vendor.js:49232:14)
    at instantiate (http://localhost:7357/assets/vendor.js:12147:24)
    at lookup (http://localhost:7357/assets/vendor.js:12019:17)
    at Object.Container.lookup (http://localhost:7357/assets/vendor.js:11951:14)
    at Context.<anonymous> (http://localhost:7357/assets/tests.js:19982:32)
    at http://localhost:7357/assets/test-support.js:2890:25
    at Object.Backburner.run (http://localhost:7357/assets/vendor.js:10865:25)
```

The problem lies [here](https://github.com/jamesarosen/ember-i18n/blob/v4.1.4/addon/services/i18n.js#L67) because the `config:environment` lookup fails unless I specifically "needs" that configuration.

I can go through and add that everywhere, or does it make sense to have a safeguard there to help people trying to use this in unit tests? Also, not sure if Rob's [commit](https://github.com/jamesarosen/ember-i18n/commit/69a799e848b0cd81905c58e1cb9fbfe56d207ae9#diff-3b81f1b52bed3c7ef73fa3edd548feaeR64) does anything to help guard this.

If nothing else, the [docs](https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Testing#unit-tests) should inform people that they need to require this.

Happy to help with a PR here, just wanted to throw out the issue and determine the community direction we want to go.

**Comment by jamesarosen** [comment]
Good catch. I would recommend adding it as one of the `needs` to the docs since that's where all of the other similar cases live.

**Comment by blimmer** [comment]
Fixed it up in the docs. Closing!
