### ISSUE TITLE
Tests: Acceptance with multiple tests

### ISSUE THREAD

**Issue by rafaltrojanowski** [jamesarosen/ember-i18n#414]
Hi, I'm dealing with problem. My guess it's related to initialization between tests.

Error:
```
beforeEach failed on visiting /search: Wrong JSON, it must have an empty key ("") with "language" and "plural-forms" information

Source: 	
Error: Wrong JSON, it must have an empty key ("") with "language" and "plural-forms" information
    at Object.loadJSON (http://localhost:7357/assets/vendor-4e07b7f714a75f73e8eb3ef0d4e36b3d.js:31:6407)
    at http://localhost:7357/assets/vendor-4e07b7f714a75f73e8eb3ef0d4e36b3d.js:68:23091
    at Array.forEach (native)
    at Object.n [as initialize] (http://localhost:7357/assets/vendor-4e07b7f714a75f73e8eb3ef0d4e36b3d.js:68:23061)
    at http://localhost:7357/assets/vendor-4e07b7f714a75f73e8eb3ef0d4e36b3d.js:6:22059
    at http://localhost:7357/assets/vendor-4e07b7f714a75f73e8eb3ef0d4e36b3d.js:6:22433
    at t (http://localhost:7357/assets/vendor-4e07b7f714a75f73e8eb3ef0d4e36b3d.js:6:30)
    at r.topsort (http://localhost:7357/assets/vendor-4e07b7f714a75f73e8eb3ef0d4e36b3d.js:6:854)
    at v._runInitializer (http://localhost:7357/assets/vendor-4e07b7f714a75f73e8eb3ef0d4e36b3d.js:6:22413)
    at v.runInitializers (http://localhost:7357/assets/vendor-4e07b7f714a75f73e8eb3ef0d4e36b3d.js:6:21947)

```

Test:
```
`import Ember from 'ember'`
`import { module, test } from 'qunit'`
`import startApp from 'ember-frontend/tests/helpers/start-app'`

module 'Acceptance: Search',
  beforeEach: ->
    @application = startApp()
    return

  afterEach: ->
    Ember.run @application, 'destroy'

test 'visiting /search', (assert) ->
  visit '/search'

  andThen ->
    assert.equal currentURL(), '/search'
    assert.equal(find('.card-content:first').text(), 'LEGO')
    shouldHaveElementWithCount(assert, '.card-content', 18)

test 'querying /search', (assert) ->
  visit '/search'

  andThen ->
    assert.equal currentURL(), '/search'

```

All suite was green with first test, when I added second scenario it has started failing. Any ideas how to approach this problem?

**Comment by jamesarosen** [comment]
I've never heard of EmberFrontend before; do you have a link to the library?

ember-i18n doesn't do any JSON deserialization. That error message doesn't come from this library. It appears to come from something called [Tryton](https://bugs.tryton.org/issue5066)

**Comment by rafaltrojanowski** [comment]
The title could be misleading, seems that it comes from ```ember-gettext```. Thanks!
